schema_version: 1

context:
  name: atlasopenmagic
  version: "1.1.0"
  python_min: '3.7'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 9cb8c98c170f472e46330d74471bd20d6ef662df8e91b509ae9b6871144041db

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=0.7
  run:
    - python >=${{ python_min }}
    - requests
    - pyyaml

tests:
  - python:
      imports:
        - atlasopenmagic
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A utility package for retrieving ATLAS open data URLs and metadata.
  homepage: https://github.com/atlas-outreach-data-tools/atlasopenmagic
  repository: https://github.com/atlas-outreach-data-tools/atlasopenmagic
  documentation: https://github.com/atlas-outreach-data-tools/atlasopenmagic
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marianaiv
    - zlmarshall
    - kratsg
